### ISSUE TITLE
UI is not responsive in smaller screens like mobile   

### ISSUE THREAD

**Issue by demonnezuko** [Karan-Malik/MovieHype#1]
In my laptop UI is looking fine but in my phone alignment of text box and background image becomes weird.
Also in phone background does not stick with scrolling instead it starts to shift towards bottom.

**Comment by Karan-Malik** [comment]
The UI of the website is made using HTML and CSS and does not use Bootstrap. This causes it to lose compatibility with phones as it does not autofit. My later websites use this auto fitting feature and are thus compatible. 
Thank you for bringing my attention to it!
